version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "37:14:bf:76:6d:8c:38:cb:3a:69:ca:c9:75:bf:08:a5"

      - checkout

      - restore_cache:
          keys:
          - v0-dependencies

      - run:
          name: install dependencies
          command: |
            if [ ! -d miniconda ]; then
              curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
              bash miniconda.sh -b -p miniconda

              export PATH=`pwd`/miniconda/bin:$PATH

              conda config --set always_yes yes --set changeps1 no
              conda config --add channels defaults
              conda config --add channels conda-forge
              conda update -q conda

              conda create -q -n test-env \
                python=3.7 \
                pip
            fi

            export PATH=`pwd`/miniconda/bin:$PATH

            conda config --set always_yes yes --set changeps1 no
            conda config --add channels defaults
            conda config --add channels conda-forge
            conda update -q conda

            source activate test-env

            conda update --all -y -q

            conda install -y -q \
              git \
              ruamel.yaml \
              pip

      - save_cache:
          paths:
            - ./miniconda
          key: v0-dependencies

      - run:
          name: run
          command: |
            export PATH=`pwd`/miniconda/bin:$PATH
            source activate test-env
            pushd code
            git clone --depth=1 https://github.com/regro/libcfgraph.git
            python run_pip_check.py


workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "30 2,8,14,20 * * *"
          filters:
            branches:
              only:
                - master
